server:
  port: ${PORT:8081}
  error:
    include-stacktrace: never

spring:
  flyway:
    baseline-on-migrate: true
    url: jdbc:${db.url}
    user: ${db.username}
    password: ${db.password}

auth:
  secret-key: CktcqpFTqLKujLr9RK4XZoAUl+6OHK5pTho8F9nWybw=
  expiration-hours: 1
db:
  host: localhost
  port: 5432
  db: paragramm
  url: postgresql://${db.host}:${db.port}/${db.db}
  username: postgres
  password: postgres