server:
  port: ${PORT:8081}
  error:
    include-stacktrace: never

spring:
  r2dbc:
    url: r2dbc:${db.url}
    username: ${db.username}
    password: ${db.password}

  flyway:
    baseline-on-migrate: true
    url: jdbc:${db.url}
    user: ${db.username}
    password: ${db.password}

auth:
  secret-key: CktcqpFTqLKujLr9RK4XZoAUl+6OHK5pTho8F9nWybw=
  expiration-hours: 1
db:
  url: postgresql://localhost:5432/paragramm
  username: postgres
  password: postgres